// <auto-generated />
using System;
using ApiyahyaFlutter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiyahyaFlutter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250710193001_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ApiyahyaFlutter.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorys");
                });

            modelBuilder.Entity("ApiyahyaFlutter.Model.Coolor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coolors");
                });

            modelBuilder.Entity("ApiyahyaFlutter.Model.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoolorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SiizeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoolorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SiizeId");

                    b.ToTable("Inventorys");
                });

            modelBuilder.Entity("ApiyahyaFlutter.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ApiyahyaFlutter.Model.Siize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Siizes");
                });

            modelBuilder.Entity("ApiyahyaFlutter.Model.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("ApiyahyaFlutter.Model.Inventory", b =>
                {
                    b.HasOne("ApiyahyaFlutter.Model.Coolor", "Coolor")
                        .WithMany("Inventories")
                        .HasForeignKey("CoolorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiyahyaFlutter.Model.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiyahyaFlutter.Model.Siize", "Siize")
                        .WithMany("Inventories")
                        .HasForeignKey("SiizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coolor");

                    b.Navigation("Product");

                    b.Navigation("Siize");
                });

            modelBuilder.Entity("ApiyahyaFlutter.Model.Product", b =>
                {
                    b.HasOne("ApiyahyaFlutter.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ApiyahyaFlutter.Model.StockMovement", b =>
                {
                    b.HasOne("ApiyahyaFlutter.Model.Inventory", "Inventory")
                        .WithMany("StockMovements")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("ApiyahyaFlutter.Model.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ApiyahyaFlutter.Model.Coolor", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("ApiyahyaFlutter.Model.Inventory", b =>
                {
                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("ApiyahyaFlutter.Model.Product", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("ApiyahyaFlutter.Model.Siize", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
