buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // تحديث الإصدار هنا ليكون متوافق مع Gradle 8.4 و Java 21
        classpath 'com.android.tools.build:gradle:8.1.1'

    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
